module.exports = {
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: 'src',
  testRegex: '.*\\.spec\\.ts$',
  transform: {
    '^.+\\.(t|j)s?$': ['@swc/jest'],
  },
  testEnvironment: 'node',
  moduleNameMapper: {
    '^src/(.*)$': '<rootDir>/$1',
  },
  collectCoverage: true,
  collectCoverageFrom: ['**/*.service.ts', '**/*.controller.ts'],
  coverageDirectory: '../coverage',
  coverageProvider: 'v8',
  coverageThreshold: {
    global: {
      statements: 98,
      branches: 90,
      functions: 99,
      lines: 98,
    },
  },
  coveragePathIgnorePatterns: [
    '\\.spec\\.ts$',
    '\\.test\\.ts$',
    '\\.dto\\.ts$',
    '\\.module\\.ts$',
    '\\.entity\\.ts$',
    '\\.constants\\.ts$',
    '\\.decorator\\.ts$',
    '\\.guard\\.ts$',
    '\\.strategy\\.ts$',
    '-enum\\.ts$',
    'generate-swagger\\.ts$',
    'main\\.ts$',
    'repl\\.ts$',
    'config/config\\.cors\\.ts$',
    'config/config\\.logger\\.ts$',
    'config/config\\.swagger\\.ts$',
    'config/env\\.validation\\.ts$',
    'common/generators/entity-generator\\.test\\.ts$',
    'common/generators/entity-generator\\.ts$',
    'common/generators/generic-mock\\.generator\\.ts$',
    'common/consts/customer\\.ts$',
    'authorization/default-config/config/default-permissions-grants-resource\\.config\\.ts$',
    'config/config\\.app\\.env\\.ts$',
    'middleware/logger\\.middleware\\.ts$',
    'common/types/prisma-transaction\\.ts$',
    'common/types/db-find-response-object\\.ts$',
    'common/types/deep-partial-object\\.ts$',
    'authentication/interfaces/authentication-with-patner\\.interface\\.ts$',
    'authentication/interfaces/jwt-payload\\.interface\\.ts$',
    '@types/global\\.d\\.ts$',
    'modules/onboardings/schemas/onboarding-dto\\.ts$',
    'src/authorization/permissions/bank-user-permissions\\.ts$',
  ],
};
