export enum DeclaredIncomeEnum {
  LESS_THAN_ONE_THOUSAND = 'LESS_THAN_ONE_THOUSAND',
  FROM_ONE_THOUSAND_TO_TWO_THOUSAND = 'FROM_ONE_THOUSAND_TO_TWO_THOUSAND',
  FROM_TWO_THOUSAND_TO_THREE_THOUSAND = 'FROM_TWO_THOUSAND_TO_THREE_THOUSAND',
  FROM_THREE_THOUSAND_TO_FIVE_THOUSAND = 'FROM_THREE_THOUSAND_TO_FIVE_THOUSAND',
  FROM_FIVE_THOUSAND_TO_TEN_THOUSAND = 'FROM_FIVE_THOUSAND_TO_TEN_THOUSAND',
  FROM_TEN_THOUSAND_TO_TWENTY_THOUSAND = 'FROM_TEN_THOUSAND_TO_TWENTY_THOUSAND',
  OVER_TWENTY_THOUSAND = 'OVER_TWENTY_THOUSAND',
}
