# Generated by Django 5.2 on 2025-05-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_account_balance_remove_account_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='maestro_client_id',
            field=models.UUIDField(null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='maestro_client_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='maestro_env',
            field=models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], null=True, max_length=20),
        ),
    ]
