# Generated by Django 5.2 on 2025-05-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tenant_maestro_client_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='maestro_client_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='maestro_env',
            field=models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], max_length=20, null=True),
        ),
    ]
